image: ubuntu:22.04

variables:
  CC: clang
  CXX: clang++

before_script:
  - apt-get update && apt-get install -y clang clang-format cmake

stages:
  - sanity
  - build
  - test

clang-format:
  stage: sanity
  script:
    - find . \( -name \*.h -o -name \*.cpp -o -name \*.hpp \) -exec clang-format --Werror --dry-run {} +

build:
  stage: build
  artifacts:
    untracked: true
    expire_in: 1 day
  script:
    - rm -rf build
    - mkdir -p build
    - cd build && cmake ..
    - make -j$(nproc)

test:
  stage: test
  dependencies: 
    - build
  script:
    - cd build && ctest
